trigger: none
  # branches:
  #   include:
  #   - main
  # paths:
  #   include:
  #     - environment/prod
  #     - environment/dev
variables:
  - group: remote_state

parameters:
  - name: env
    displayName: Select the environment
    type: string
    default: dev
    values:
      - dev
      - prod

pool:
  name: maagents
stages:
- stage: BuildStage
  jobs:
  - job: Tflintscanning
    displayName: Tflint Scanning
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $url = "https://github.com/terraform-linters/tflint/releases/latest/download/tflint_windows_amd64.zip"
          $out = "$(Agent.TempDirectory)\tflint.zip"
          Invoke-WebRequest -Uri $url -OutFile $out
          
          
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          pip install checkov
          checkov --version
          checkov -d "$(System.DefaultWorkingDirectory)/environments/${{ parameters.env }}"

    

  - job: TerraformInitialization
    displayName: Terraform Initialization
    steps:
    - task: TerraformInstaller@1
      displayName: Terraform Install
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/${{ parameters.env }}'
        backendServiceArm: 'Appserviceconn'
        backendAzureRmResourceGroupName: $(rg_name)
        backendAzureRmStorageAccountName: $(stg_name)
        backendAzureRmContainerName: $(container_name)
        backendAzureRmKey: '${{ parameters.env }}apstate.tf'
    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/${{ parameters.env }}'
        environmentServiceNameAzureRM: 'Appserviceconn'
- stage: DeployStage
  dependsOn:
  - BuildStage
  jobs:
  - job: ManualValidation
    displayName: Manual Validation
    pool:
      name: server
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'mayank17717@gmail.com'
        onTimeout: 'resume'
  - job: TerraformApply
    dependsOn:
    - ManualValidation
    pool:
      name: maagents
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/${{ parameters.env }}'
        backendServiceArm: 'Appserviceconn'
        backendAzureRmResourceGroupName: 'ggbackend'
        backendAzureRmStorageAccountName: 'ggstginfra'
        backendAzureRmContainerName: 'backend'
        backendAzureRmKey: '${{ parameters.env }}apstate.tf'
    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/${{ parameters.env }}'
        environmentServiceNameAzureRM: 'Appserviceconn'
